### ISSUE TITLE
Stack execution issue

### ISSUE THREAD

**Issue by reziakk** [aws-samples/amazon-chime-sma-bridging#23]
Hi, I've tried a couple of times to deploy it on my environment.  However, when it is supposed to execute the cloudformation it throws an error. All steps have been executed as per described. It goes well until the last part. Some information have been modified for security measures.

Do you wish to deploy these changes (y/n)? y
AmazonChimeSDKPSTNAudioBridging: deploying... [1/1]
[0%] start: Publishing 350185a1069fa20a23a583e20c77f6844218bd73097902362dc94f1a108f5d89:3685xxxxxxxx-us-east-1
[0%] start: Publishing 679066847909511778943bd4d081cd2468b890d5fc1272dd1fb101adb17c9b0d:3685xxxxxxxx-us-east-1
[0%] start: Publishing 2bc265c5e0569aeb24a6349c15bd54e76e845892376515e036627ab0cc70bb64:3685xxxxxxxx-us-east-1
[0%] start: Publishing f4fb2f27589bf03d356696391a5b5c1c727ccd522404a5ba545d923ee146ede5:3685xxxxxxxx-us-east-1
[0%] start: Publishing 1e85bcd7774f4f9e640d34759bef652508e0ebc55cb6d2b6cdb8600fa9ab8e3b:3685xxxxxxxx-us-east-1
[0%] start: Publishing e8fea7e029780f03a78580d41b7ffbc4551d6e7d6caa190a451880191c166189:3685xxxxxxxxus-east-1
[0%] start: Publishing 450492823b610a516be3417bc8871e9158b4d395a5ae9e714f086ce8f1e6cfaf:3685xxxxxxxx-us-east-1
[0%] start: Publishing 7b4d8328d248e717610280f94dc24898fdfa7f146af3eaba11ef1bb666b03392:3685xxxxxxxx-us-east-1
[0%] start: Publishing 4f757a880e2a135a919ab66d9aaa2f958b997b752bcc66621d1ba3e642c2e4e0:3685xxxxxxxx-us-east-1
[11%] success: Published 7b4d8328d248e717610280f94dc24898fdfa7f146af3eaba11ef1bb666b03392:3685xxxxxxxx-us-east-1
[22%] success: Published 2bc265c5e0569aeb24a6349c15bd54e76e845892376515e036627ab0cc70bb64:3685xxxxxxxx-us-east-1
[33%] success: Published 450492823b610a516be3417bc8871e9158b4d395a5ae9e714f086ce8f1e6cfaf:3685xxxxxxxx-us-east-1
[44%] success: Published 679066847909511778943bd4d081cd2468b890d5fc1272dd1fb101adb17c9b0d:3685xxxxxxxx-us-east-1
[55%] success: Published e8fea7e029780f03a78580d41b7ffbc4551d6e7d6caa190a451880191c166189:3685xxxxxxxx-us-east-1
[66%] success: Published 4f757a880e2a135a919ab66d9aaa2f958b997b752bcc66621d1ba3e642c2e4e0:3685xxxxxxxx-us-east-1
[77%] success: Published 1e85bcd7774f4f9e640d34759bef652508e0ebc55cb6d2b6cdb8600fa9ab8e3b:3685xxxxxxxx-us-east-1
[88%] success: Published f4fb2f27589bf03d356696391a5b5c1c727ccd522404a5ba545d923ee146ede5:3685xxxxxxxx-us-east-1
[100%] success: Published 350185a1069fa20a23a583e20c77f6844218bd73097902362dc94f1a108f5d89:3685xxxxxxxx-us-east-1

 ❌  AmazonChimeSDKPSTNAudioBridging failed: Error: No stack named 'AmazonChimeSDKPSTNAudioBridging'
    at CloudFormationStack.assertExists (C:\Users\user.name\amazon-chime-sma-bridging\node_modules\aws-cdk\lib\index.js:361:18685)
    at get stackId [as stackId] (C:\Users\user.name\amazon-chime-sma-bridging\node_modules\aws-cdk\lib\index.js:361:17910)
    at tryHotswapDeployment (C:\Users\user.name\amazon-chime-sma-bridging\node_modules\aws-cdk\lib\index.js:361:25694)  
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deployStack (C:\Users\user.name\amazon-chime-sma-bridging\node_modules\aws-cdk\lib\index.js:367:651)       
    at async deployStack2 (C:\Users\user.name\amazon-chime-sma-bridging\node_modules\aws-cdk\lib\index.js:374:145469)   
    at async C:\Users\user.name\amazon-chime-sma-bridging\node_modules\aws-cdk\lib\index.js:374:128787
    at async run (C:\Users\user.name\amazon-chime-sma-bridging\node_modules\aws-cdk\lib\index.js:374:126793)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: No stack named 'AmazonChimeSDKPSTNAudioBridging'
    at deployStacks (C:\Users\user.name\amazon-chime-sma-bridging\node_modules\aws-cdk\lib\index.js:374:129094)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CdkToolkit.deploy (C:\Users\user.name\amazon-chime-sma-bridging\node_modules\aws-cdk\lib\index.js:374:147518)
    at async exec4 (C:\Users\user.name\amazon-chime-sma-bridging\node_modules\aws-cdk\lib\index.js:429:51795)

Stack Deployments Failed: Error: No stack named 'AmazonChimeSDKPSTNAudioBridging'

**Comment by reziakk** [comment]
Just for reference, I've made the cloning and yarn launch from scratch. 
It throws the following in the last step:
Subprocess exited with error 2147483651
👾 Task "build » post-compile » synth:silent" failed when executing "cdk synth -q" (cwd: C:\Users\user.name\amazon-chime-sma-bridging)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
👾 Task "launch" failed when executing "yarn && yarn projen && yarn build && yarn cdk bootstrap && yarn cdk deploy --hotswap" (cwd: C:\Users\thiago.mesquita\amazon-chime-sma-bridging)
error Command failed with exit code 1.

**Comment by schuettc** [comment]
Was having an issue with the `hotswap` option.  Have updated and made a few changes with https://github.com/aws-samples/amazon-chime-sma-bridging/commit/1510f2c1ec31f75cc8d11114399e5fc871a2e645.  Can you pull and try again?
